name: himtika_apps
version: 1.0.0+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_dotenv: ^5.0.2
  supabase_flutter: ^0.3.1+3
  freezed_annotation: ^2.0.3
  flutter_riverpod: ^1.0.3
  open_mail_app: ^0.4.5
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  bordered_text: 2.0.0
  carousel_slider: ^4.1.1
  awesome_dialog: ^2.2.1
  rflutter_alert: 2.0.4
  auto_size_text: 3.0.0
  sliding_up_panel: 2.0.0+1
  intl: ^0.17.0
  flutter_datetime_picker: 1.5.1
  syncfusion_flutter_pdfviewer: ^19.4.54-beta
  pdfx: ^2.0.1+2
  expandable: 5.0.1
  get_storage: 2.0.3
  cached_network_image: 3.0.0
  introduction_screen: ^3.0.2
  url_launcher: ^6.1.3
  shimmer: 2.0.0
  smooth_page_indicator: 1.0.0+2
  youtube_player_flutter: 8.0.0
  flutter_html: 2.2.1
  bubble: 1.2.1
  flutter: 
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  flutter_local_notifications: ^9.5.3+1
  onesignal_flutter: ^3.3.2
  profanity_filter: ^2.0.0
  upgrader: ^4.2.1

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies: 
  flutter_lints: ^1.0.0
  dependency_validator: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/icon/
    - .env.prod
    - .env.dev
  uses-material-design: true

